name: 'WordPress Theme SVN Deploy'
description: 'Deploy to the WordPress Theme Repository'
author: 'shopeo'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
